tap "nikitabobko/tap"
# CLI for working with C2PA manifests and media assets
brew "c2patool"
# Create and run Linux containers using lightweight virtual machines
brew "container", restart_service: :changed
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# GitHub command-line tool
brew "gh"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Command-line utility for Home Assistant
brew "homeassistant-cli"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@77"
# Read the content info of a DVD
brew "lsdvd"
# Mac App Store command-line interface
brew "mas"
# Metadata anonymization toolkit
brew "mat2"
# NCurses Disk Usage
brew "ncdu"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Rsync for cloud storage
brew "rclone"
# Utility that provides fast incremental file transfer
brew "rsync"
# Terminal multiplexer
brew "tmux"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Tool for managing your YubiKey configuration
brew "ykman"
cask "nikitabobko/tap/aerospace"
# Official eID-Client of the Federal Government of Germany
cask "ausweisapp"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# App for managing battery charging. (Also installs a CLI on first use.)
cask "battery"
# Desktop password and login vault
cask "bitwarden"
# Bluetooth Low Energy browser
cask "bluetility"
# E-books management software
cask "calibre"
# Photography workflow application and raw developer
cask "darktable"
# Run Stable Diffusion locally
cask "diffusionbee"
# App to build and share containerised applications and microservices
cask "docker-desktop"
# Matrix collaboration client
cask "element"
# Email client
cask "fastmail"
# Web browser
cask "firefox"
# Free and open-source image editor
cask "gimp"
# Desktop client for GitHub repositories
cask "github"
# Virtual globe
cask "google-earth-pro"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Password manager app
cask "keepassxc"
# Tool to show what is persistently installed on the computer
cask "knockknock"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Multi-platform web browser
cask "microsoft-edge"
# Spreadsheet software
cask "microsoft-excel"
# Email client
cask "microsoft-outlook"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Word processor
cask "microsoft-word"
# Untraceable cryptocurrency wallet
cask "monero-wallet"
# Desktop sync client for Nextcloud software products
cask "nextcloud"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Cloud storage client
cask "onedrive"
# EPUB ebook editor
cask "sigil"
# Instant messaging application focusing on security
cask "signal"
# Web browser focusing on security
cask "tor-browser"
# Companion app for the Trezor hardware wallet
cask "trezor-suite"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# App that provides drivers for older model scanners that are no longer supported
cask "vuescan"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Full-featured companion app to the YubiKey
cask "yubico-authenticator"
# Gecko based web browser
cask "zen"
mas "Apple Configurator", id: 1037126344
mas "Home Assistant", id: 1099568401
mas "TK-Safe", id: 1592438228
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
cargo "bandwhich"
cargo "bat"
cargo "bottom"
cargo "difftastic"
cargo "du-dust"
cargo "dua-cli"
cargo "dutree"
cargo "dysk"
cargo "erdtree"
cargo "eza"
cargo "fd-find"
cargo "git-delta"
cargo "iamb"
cargo "license-generator"
cargo "macchina"
cargo "mdbook"
cargo "mdbook-admonish"
cargo "mdbook-katex"
cargo "mdbook-linkcheck"
cargo "mdbook-toc"
cargo "mdcat"
cargo "miniserve"
cargo "monolith"
cargo "procs"
cargo "ripgrep"
cargo "rm-improved"
cargo "rustic-rs"
cargo "sd"
cargo "svg-invert"
cargo "tailspin"
cargo "xcp"
