# https://iamb.chat/configure.html?highlight=sync

[profiles.user]
user_id = "@ben:sudo.is"

[settings]
request_timeout = 180
user_gutter_width = 12
username_display = "localpart"
typing_notice_display = true
reaction_display = true
message_user_color = true
# Display Emojis with their shortcodes
message_shortcode_display = false
reaction_shortcode_display = false

[settings.sort]
members = ["power", "id"]
rooms = ["favorite", "unread", "recent", "name", "alias", "lowpriority"]
dms = ["favorite", "unread", "name", "lowpriority"]
# defaults to 'rooms' value
#chats = []
#spaces = []

[settings.image_preview]
protocol.type = "sixel"

[settings.notifications]
enabled = false
